### ISSUE TITLE
set_optimizer_attribute() issue

### ISSUE THREAD

**Issue by kocvara** [jump-dev/MosekTools.jl#95]
Julia 1.7.1
The following piece of code
```julia
model = read_from_file("../../../sdplib/theta1.dat-s")
set_optimizer(model, Mosek.Optimizer)
set_optimizer_attribute(model,"MSK_IPAR_INTPNT_SOLVE_FORM", MosekTools.MSK_SOLVE_DUAL)
```
gives error message
```
ERROR: MethodError: no method matching map_indices(::MathOptInterface.Utilities.var"#7#8"{MathOptInterface.Utilities.IndexMap}, ::Mosek.Solveform)
```
This works:
```julia
model = Model(with_optimizer(Mosek.Optimizer,  MSK_IPAR_INTPNT_SOLVE_FORM  = MosekTools.MSK_SOLVE_DUAL));
```
but then I don't know how to read the SDPA file into the existing model.

**Comment by blegat** [comment]
Which version of MathOptInterface are you using ?
This should have been fixed in https://github.com/jump-dev/MathOptInterface.jl/pull/1672

**Comment by kocvara** [comment]
[b8f27783] MathOptInterface v0.9.22

I updated all and the problem is still there

**Comment by blegat** [comment]
```julia
julia> using JuMP

julia> model = read_from_file("theta1.dat-s")
A JuMP Model
Minimization problem with:
Variables: 104
Objective function type: AffExpr
`Vector{AffExpr}`-in-`MathOptInterface.PositiveSemidefiniteConeTriangle`: 1 constraint
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> set_optimizer(model, Mosek.Optimizer)

julia> set_optimizer_attribute(model,"MSK_IPAR_INTPNT_SOLVE_FORM", MosekTools.MSK_SOLVE_DUAL)

(MosekTools) pkg> st
     Project MosekTools v0.12.1
      Status `~/.julia/dev/MosekTools/Project.toml`
  [4076af6c] JuMP v1.0.0
  [b8f27783] MathOptInterface v1.1.1
  [6405355b] Mosek v1.2.2
  [de0858da] Printf
```
I cannot reproduce with the latest version.
Have you restarted Julia after updating ?

**Comment by kocvara** [comment]
I have. But I see that all your versions are newer than mine (you being a developer?). This might be a silly problem on my side, sorry if it is, I am just using

(@v1.7) pkg> update 

 and get 

[4076af6c] JuMP v0.21.4
  [b8f27783] MathOptInterface v0.9.22
  [1ec41992] MosekTools v0.9.4

**Comment by blegat** [comment]
There are still a few packages not supporting MathOptInterface v0.10 so one of them might have you blocked behind.
We [just released MathOptInterface v1.0 and JuMP v1.0](https://jump.dev/blog/1.0.0-release/) so hopefully once all packages have gotten up to speed, this won't happen too much in the future. The major ones have already been updated see https://github.com/jump-dev/JuMP.jl/issues/2564

**Comment by odow** [comment]
Closing because this seems fixed.
